modules/economic_account_act/models/Order.php
<?php

namespace app\modules\economic_account_act\models;

use Yii;

/**
 * This is the model class for table "order".
 *
 * @property int $id
 * @property double $quantity
 * @property int $account_id
 * @property int $service_id
 *
 * @property Account $account
 * @property Service $service
 */
class Order extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['quantity'], 'number'],
            [['account_id', 'service_id'], 'required'],
            [['account_id', 'service_id'], 'integer'],
            [['account_id'], 'exist', 'skipOnError' => true, 'targetClass' => Account::className(), 'targetAttribute' => ['account_id' => 'id']],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => Service::className(), 'targetAttribute' => ['service_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Номер заказа',
            'quantity' => 'Количество',
            'account_id' => 'Счет',
            'service_id' => 'Услуга',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccount()
    {
        return $this->hasOne(Account::className(), ['id' => 'account_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(Service::className(), ['id' => 'service_id']);
    }

}

modules/economic_account_act/controllers/AccountController.php
<?php

namespace app\modules\economic_account_act\controllers;

use Yii;
use app\modules\economic_account_act\models\Account;
use app\modules\economic_account_act\models\AccountSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \Datetime;
use app\modules\economic_account_act\models\Order;

/**
 * AccountController implements the CRUD actions for Account model.
 */
class AccountController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Account models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AccountSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Account model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
	    $orders = Order::find()
			->where(['account_id' => $id])->all();			

			
        return $this->render('view', [
            'model' => $this->findModel($id), 'orders' => $orders
        ]);
    }

    /**
     * Creates a new Account model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Account();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			//После сохранения прямиком к оформлению заказов
			return  Yii::$app->response->redirect(array('accounts/order/index','account_id'=>$model->id));
			
        }
		

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Account model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
			//После сохранения прямиком к оформлению заказов
			return  Yii::$app->response->redirect(array('accounts/order/index','account_id'=>$model->id));
			
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Account model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Account model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Account the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Account::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/economic_account_act/controllers/OrderController.php
<?php

namespace app\modules\economic_account_act\controllers;

use Yii;
use app\modules\economic_account_act\models\Order;
use app\modules\economic_account_act\models\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex($account_id)
    {
        $searchModel = new OrderSearch();
		$searchModel -> account_id = $account_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'account_id' => $account_id
        ]);
    }


    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Order();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
   
			$searchModel = new OrderSearch();
			$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		
			 return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'account_id' => $model->account_id
        ]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

  

    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

		  $model = $this->findModel($id);

           $searchModel = new OrderSearch();
			$dataProvider = $searchModel->search(Yii::$app->request->queryParams);

		
			 return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
			'account_id' => $model->account_id
        ]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/economic_account_act/views/order/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\modules\economic_account_act\models\Service;
use app\modules\economic_account_act\models\Account;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\modules\economic_account_act\models\Order */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-form">

    <?php $form = ActiveForm::begin(); 
		$model -> account_id = Yii::$app->getRequest()->getQueryParam('account_id');
	?>
  
	<?= $form->field($model, 'service_id')->dropDownList(
			ArrayHelper::map(Service::find()->all(), 'id', function($element) {
			return $element->name.', Цена:			'.$element['price'].' ('.$element['measurement_unit'].')';
	})) ?>
	


	<?= $form->field($model, 'account_id')->textInput( ['readOnly'=> true]) ?>
		  
		
    <?= $form->field($model, 'quantity')->textInput() ?>

	
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/economic_account_act/views/order/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\economic_account_act\models\OrderSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'quantity') ?>

    <?= $form->field($model, 'account_id') ?>

    <?= $form->field($model, 'service_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('По умолчанию', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/economic_account_act/views/order/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\economic_account_act\models\Order */
$account = Yii::$app->getRequest()->getQueryParam('account_id');
$this->title = 'Создать заказ';
$this->params['breadcrumbs'][] = ['label' => 'Счет №'.$account];
$this->params['breadcrumbs'][] = ['label' => 'Заказы'];
$this->params['breadcrumbs'][] = $this->title;
?>

<?php echo Html::a('Счет №'.$account, ['account/update', 'id' => $account ], ['class' => 'btn btn-lg btn-success']);  ?>

<?php echo Html::a('Заказы', ['index', 'account_id' => $account], ['class' => 'btn btn-lg btn-success']);  ?>

		
<div class="order-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/economic_account_act/views/order/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\economic_account_act\models\OrderSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->params['breadcrumbs'][] = ['label' => 'Счет №'.Yii::$app->getRequest()->getQueryParam('account_id')];
$this->title = 'Заказы по счету №'.$account_id;
$this->params['breadcrumbs'][] = $this->title;

$account = Yii::$app->getRequest()->getQueryParam('account_id');

echo Html::a('Счет №'.$account, ['account/update', 'id' => $account ], ['class' => 'btn btn-lg btn-success']);  
?>
<div class="order-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать заказ', ['create',  'account_id' => $account_id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'quantity',
            'account_id',
			 [
            'header' => $searchModel -> attributeLabels()['service_id'],
            'attribute' => 'service.name'
			],
            ['class' => 'yii\grid\ActionColumn', 'template'=>'{delete}' ],
        ],
    ]); ?>
</div>